name: Docker Image CI

on:
  push:
    branches:
    - main      

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4.2.2
    - 
      name: Login to DockerHub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Set Docker Metadata
      id: docker_meta
      uses: docker/metadata-action@v5.7.0
      with:
        images: n0wst4ndup/openlaw-mcp
    -
      name: Build and Push
      uses: docker/build-push-action@v6.16.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
